# Generated by Django 5.0.6 on 2025-06-27 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del curso')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('duracion_horas', models.IntegerField(verbose_name='Duración (horas)')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('en línea', 'En línea')], max_length=50, verbose_name='Modalidad')),
                ('disponible', models.BooleanField(default=True, verbose_name='¿Disponible?')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos', verbose_name='Imagen del curso')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizado', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['creado'],
            },
        ),
    ]
